name: Daily Avatar Rendering

on:
  schedule:
    - cron: '0 2 * * *'  # every day at 2:00 AM UTC
  workflow_dispatch:

jobs:
  render-avatar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t sadtalker-job .

    - name: Create results directory
      run: mkdir -p results

    - name: Run Avatar Generation in Docker
      run: |
        docker run --rm -v ${{ github.workspace }}/results:/app/results \
        sadtalker-job

    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: rendered-video
        path: results/
