name: Daily Avatar Rendering

on:
  schedule:
    - cron: '0 4 * * *'  # every day at 2:00 AM UTC
  workflow_dispatch:

jobs:
  render-avatar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run avatar generation
      run: |
        python inference.py --driven_audio telugu_audio.wav --source_image myavatar.jpg --enhancer gfpgan --result_dir results/
